name: Run Robot Framework Tests

on:
  push:
    branches:
      - main  # o la rama que desees utilizar
  pull_request:
    branches:
      - main  # o la rama que desees utilizar

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2' 

        - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1' 

      - name: Install dependencies 
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-browser


      - name: Initialize Robot Framework Browser
        run: |
          rfbrowser init
      

      - name: Run Robot Framework tests ui
        run: |
          robot ui
      - name: Run Robot Framework tests api
        run: |
          robot apis
